apiVersion: v1
kind: ConfigMap
metadata:
  name: bakery-config
  labels:
    app: bakery-stock
data:
  # Database configuration
  DB_HOST: "mysql-service"
  DB_NAME: "bakery_db"
  DB_USER: "bakery_user"
  DB_PORT: "3306"

  # Products service
  PRODUCTS_PORT: "5001"

  # Orders service
  ORDERS_PORT: "5002"

  # Stock service
  STOCK_PORT: "5003"
